# This file is used to configure the Rokkit installer. these will appear in the installer menu as sections>options>description
# # The options are scripts that will be run when the user selects them.
# # The scripts are located in the scripts directory and are named after the option.
  - title: "Cider V2"
    options: 
      - name: "Cider V2"
        description: "An unofficial apple music client"
        script: "install_cider.sh"

  - title: "Disable on USB device"
    options:
      - name: "Disable USB devices"
        description: "This will disable devices that prevent the system from sleeping, such as USB devices that are not in use."
        script: "disable_usb.sh"

  - title: "Internal storage"
    options:
      - name: "Mount drive at boot"
        description: "Mount the internal storage drive at boot. This is useful for systems with multiple drives. It will mount the drive at /mnt/storage."
        script: "mounting_drive.sh"

  - title: "Shell"
    options:
      - name: "Rokkit"
        description: "- Set ZSH as the default shell for the user. - Install oh-my-zsh with plugins: zsh-autosuggestions, zsh-syntax-highlighting, zsh-completions, z. - Install the Catppuccin Mocha theme for ZSH. - Install powerlevel10k theme for ZSH. - Set up custom keybindings and aliases for ZSH."
        script: "setting_up_zsh.sh"

  - title: "LazyVim"
    options:
      - name: "Install LazyVim"
        description: "Install LazyVim, a Neovim configuration that provides a modern and feature-rich development environment."
        script: "install_lazyvim.sh"


