base_panels:
  navigation: &base_nav_panel
    id: 0
    title: Navigation
    format: nav
    x: 1
    y: 4
    width: 60
    height: 6
    padding-x: 2
    padding-y: 1

  section: &base_section_panel
    id: 1
    title: Sections
    format: section
    x: 1
    y: 10
    width: 30
    height: 20
    padding-x: 2
    padding-y: 1

  option: &base_option_panel 
    id: 2
    title: Options
    format: option
    x: 32
    y: 10
    width: 40
    height: 20
    padding-x: 2
    padding-y: 1

  description: &base_description_panel
    id: 3
    title: Descriptions
    format: description
    x: 73
    y: 10
    width: 50
    height: 20
    padding-x: 2
    padding-y: 1

  action: &base_action_panel
    id: 4
    title: Actions
    format: action
    x: 62
    y: 4
    width: 61
    height: 6
    padding-x: 2
    padding-y: 1

  log: &base_log_panel
    id: 5
    title: Log
    format: log
    x: 1
    y: 30
    width: 122
    height: 16
    padding-x: 2
    padding-y: 1

pages:
  - id: 0
    title: Packages
    panels:
      - *base_nav_panel
      - *base_description_panel
      - *base_section_panel
      - *base_option_panel
      - *base_action_panel
      - *base_log_panel

  - id: 1
    title: Configuration
    panels:
      - *base_nav_panel
      - *base_description_panel
      - *base_section_panel
      - *base_option_panel
      - *base_action_panel
      - *base_log_panel
