package packages

var SECTIONS = map[string][]string{
	"Desktop Environment": {
		"hyprland",
		"hyprlock",
		"hyprpicker",
		"hyprpaper",
		"hypridle",
		"hyprshot",
		"swaync",
		"waybar",
		"wlogout",
		"wofi",
		"firefox",
		"thunar",
		"kitty",
		"zsh",
		"gwenview",
	},
	"AUR Helpers": {
		"yay",
		"paru",
	},
	"Media": {
		"discord",
		"qbittorrent",
		"thunderbird",
		"steam",
		"obs-studio",
		"obsidian",
		"vlc",
	},
	"Development": {
		"git",
		"neovim",
		"docker",
		"mariadb",
		"go",
		"rust",
		"nodejs",
	},
	"System Utilities": {
		"wget",
		"curl",
		"neofetch",
		"nvtop",
		"htop",
		"radeontop",
		"nwg-look",
		"man-db",
		"man-pages",
	},
	"Environment Styling": {
		"adw-gtk-theme",
		"papirus-icon-theme",
		"catppuccin-gtk-theme-mocha",
		"catppuccin-sddm-theme-mocha",
		"ttf-font-awesome",
		"ttf-ubuntu-mono-nerd",
		"ttf-ubuntu-nerd",
		"simple-sddm-theme-2-git",
		"simple-sddm-theme-git",
	},
	"Configurations": {
		"lazyvim",
		"hyprland",
		"custom cider install",
		"custom drive mounting",
		"enable wakeup service",
		"enable bluetooth",
		"ZSH as default shell",
		"Oh-My-ZSH",
		"ZSH plugins",
		"Powerlevel10k",
		"kitty config",
		"sddm_theme",
		"grub theme",
	},
}
